### ISSUE TITLE
Game world stops updating at specific coordinates

### ISSUE THREAD

**Issue by Ionaru** [EnigmaticaModpacks/Enigmatica8#97]
### Modpack Version

1.0.5

### Describe your issue.

In both singleplayer and multiplayer, if I go to specific coordinates in a specific world, the game world stops rendering, ticking, and being interactable in general.

In Multiplayer, the server will detect a crash after 60 seconds and restart itself. In singleplayer the game stays open but does not recover from the issue, pressing save & quit will cause the game to hang on "saving world".

Seed: `4753947492036150903`

Coordinates: `8294` `69` `-78130` will instantly hang.

Coordinates `8193` `60`, `-78326` will initially render the world, until what I suspect a bad chunk is hit.

![2022-03-04_16 02 25](https://user-images.githubusercontent.com/3472373/156787126-f21e550d-e537-4274-bc2f-e51c876fdb7e.png)

### Crash Report

https://gist.github.com/Ionaru/03cbf65d87206edc4f03a97b3c38fcd3

### Latest Log

https://gist.github.com/Ionaru/d5abd8a7949185499fcb12c681497781

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thanks for the report! I'm fairly certain this is caused by the generation of a huge structure, I plan to reduce max size to help with this :)

**Comment by Ionaru** [comment]
Do you know what mod is causing it and can I change something in the server configs to 'fix' it for now?

The server crashing each time anyone gets close to that area is rapidly becoming troublesome.

**Comment by NillerMedDild** [comment]
When Dungeons Arise, it also happened in E6: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/3992#issuecomment-1036606917

**Comment by NillerMedDild** [comment]
If you decrease the size of structures through the config, it should fix it. I recommend reducing everything above 50 to 50.

**Comment by Ionaru** [comment]
I changed the config so all `*Size` options are 50 or below, but it did not appear to fix the issue in SP.

**Comment by NillerMedDild** [comment]
Damn 🤔 since the structure was already generating it might not respect the config change removing the mod ought to work though.

**Comment by Ionaru** [comment]
It doesn't seem to be caused by the When Dungeons Arise mod. I removed it and the world still freezes at those coordinates.

I'm testing with a newly generated world each time, seed is in the initial report.

**Comment by NillerMedDild** [comment]
Strange 🤔 does a structure still generate at those coordinates with When Dungeons Arise removed?

**Comment by Ionaru** [comment]
None aboveground.

**Comment by NillerMedDild** [comment]
That is odd. Could you please supply your debug.log file?

**Comment by ZephyrWindSpirit** [comment]
Taking out the mod isn’t going to remove the structure as its made from vanilla blocks. Its possible, and I’ve had it happen myself, that the forge ‘config corrector’ for nature’s starlight and mekanism tools is constantly correcting itself? Thats the source of about half my freezes.

**Comment by Ionaru** [comment]
> Alright. Could you please supply your debug.log file?

Where do I find that?

**Comment by NillerMedDild** [comment]
In your logs folder, hopefully. If you use CurseForge it may be disabled.

**Comment by Ionaru** [comment]
Debug.log: https://gist.github.com/Ionaru/4061d9bc020c3c53ed09a6b88d576e53

**Comment by NillerMedDild** [comment]
Thanks! This suggestion is a bit out there, but would you mind removing Extreme Reactors and see if it still happens?

**Comment by Ionaru** [comment]
It still happens with Extreme Reactors removed.

**Comment by NillerMedDild** [comment]
Noo damn :P May I have the new debug.log please?

**Comment by Ionaru** [comment]
https://gist.github.com/Ionaru/00f5472675d9e6bb22b4f99ed79e5ac0

**Comment by NillerMedDild** [comment]
I don't see anything indicating stopping/hanging in there even ><

**Comment by Ionaru** [comment]
This may be the same issue (or related to it) as https://github.com/TeamAOF/All-of-Fabric-5/issues/193
